name: web-cloner
services:
- name: web
  source_dir: /
  github:
    repo: samyakjain-1/website-clone
    branch: main
  dockerfile_path: Dockerfile
  instance_count: 1
  instance_size_slug: basic-xs
  env:
  - key: NODE_ENV
    value: production
  - key: OPENAI_API_KEY
    scope: RUN_TIME
    type: SECRET 